[package]
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
description = "Linux SocketCAN library. Send and receive CAN frames via CAN bus on Linux."
documentation = "https://docs.rs/socketcan"
license = "MIT"
name = "socketcan"
repository = "https://github.com/mbr/socketcan-rs"
version = "2.0.0"

[dependencies]
byte_conv = "0.1.1"
futures = "0.1.16"
hex = "^0.3"
itertools = "^0.4"
libc = "^0.2"
mio = "0.6.6"
netlink-rs = { git = "https://github.com/netlink-rs/netlink-rs", rev = "c008b4e385e3c0a114ec907ca28ad4fe33233ed5" }
nix = "^0.5"
tokio-core = "0.1.7"
tokio-io = "0.1.3"
try_from = "0.2.0"

[features]
vcan_tests = []
